# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:

- script: |
    # gpg --list-keys
    # cd /Users/rakeshkumarmallam/imagesigning
    # export PASSWORD="rakesh123"
    export GPG_TTY=$(tty)
    # expect -c "                                                            
    skopeo copy --sign-by rakesh@mallam.com docker://docker.io/mallam/my-centos:dev docker://rakesh.azurecr.io/mallam/my-centos:dev
    # expect \"Passphrase: \"
    # sleep 10
    # send \"$PASSWORD\n\"
    # interact
    # "
  displayName: 'Run a multi-line script'
