# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:

- script: |
    gpg --list-keys
    cd /Users/rakeshkumarmallam/imagesigning
    # PASSWORD="rakesh123"
    # expect -c "                                                            
    spawn skopeo copy --sign-by rakesh@mallam.com docker://docker.io/openshift/observe docker://rakesh.azurecr.io/mallam/observe:1.0.2
    # expect \"Passphrase: \"
    # sleep 3
    # send   \"$PASSWORD\n\"
    # interact
    # "
  displayName: 'Run a multi-line script'
